# Generated by Django 3.1.4 on 2020-12-30 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('value', models.FloatField(default=0)),
                ('budget', models.FloatField(default=5000000.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('age', models.IntegerField(default=0)),
                ('market_value', models.FloatField(default=1000000.0)),
                ('position', models.CharField(choices=[('GOALKEEPER', 'GOALKEEPER'), ('DEFENDER', 'DEFENDER'), ('MIDFIELDER', 'MIDFIELDER'), ('ATTACKER', 'ATTACKER')], max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer_manager.team')),
            ],
        ),
        migrations.CreateModel(
            name='MarketList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer_manager.player')),
            ],
        ),
    ]
