# Generated by Django 3.1.4 on 2020-12-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='player',
            name='asked_price',
            field=models.FloatField(default=0),
        ),
    ]
