# Generated by Django 3.1.4 on 2021-01-04 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_manager', '0002_auto_20201231_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='asked_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='market_value',
            field=models.FloatField(default=1000000.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='budget',
            field=models.FloatField(default=5000000.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='value',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
